In [29]:
import pandas as pd
import numpy as np
import re

In [3]:
path = 'DOUBLE MAJOR/MIS.xlsx'

In [4]:
df = pd.read_excel(path)

#### Explore data

In [5]:
print(df.head())

                Column1      Column2                  Column3 Column4  \
0                    TT  MÃ HỌC PHẦN             TÊN HỌC PHẦN   SỐ TC
1                   NaN          NaN                      NaN     NaN
2  1. Giáo dục thể chất          NaN                      NaN     NaN
3              Bắt Buộc          NaN                      NaN     NaN
4                     1     GDTC1101  Giáo dục thể chất 1 (*)       2

   Column5 Column6              Column7             Column8  \
0  SỐ TIẾT     NaN  HỌC PHẦN TIÊN QUYẾT  HỌC PHẦN HỌC TRƯỚC
1       LT      TH                  NaN                 NaN
2      NaN     NaN                  NaN                 NaN
3      NaN     NaN                  NaN                 NaN
4       30     NaN                  NaN                 NaN

              Column9  Column10
0         KHOA/BỘ MÔN  ĐỀ CƯƠNG
1                 NaN       NaN
2                 NaN       NaN
3                 NaN       NaN
4  Các đơn vị đào tạo       NaN

#### Drop the rows and Columns that are not the part of the actual data

In [22]:
df = df.drop([0,1], axis = 0)

In [23]:
df = df.drop(df.columns[[4,5,6,7,9]], axis = 1)

In [24]:
df

,Column1,Column2,Column3,Column4,Column9
2,1. Giáo dục thể chất,NaN,NaN,NaN,NaN
3,Bắt Buộc,NaN,NaN,NaN,NaN
4,1,GDTC1101,Giáo dục thể chất 1 (*),2,Các đơn vị đào tạo
5,Tự Chọn,NaN,NaN,NaN,NaN
6,2,GDTC1103,Bóng chuyền 1 (*),2,Các đơn vị đào tạo
...,...,...,...,...,...
111,89,TIHT1122,Quản trị tri thức,3,Viện Công nghệ thông tin và Kinh tế số
112,90,TIHT1123,Ứng dụng trí tuệ nhân tạo trong kinh doanh và ...,3,Viện Công nghệ thông tin và Kinh tế số
113,91,TIKT1106,Mạng và truyền thông,3,Viện Công nghệ thông tin và Kinh tế số
114,92,TIKT1129,Hệ thống thương mại điện tử,3,Viện Công nghệ thông tin và Kinh tế số
115,93,TIKT1134,Phát triển các ứng dụng WEB,3,Viện Công nghệ thông tin và Kinh tế số

#### Rename the columns

In [28]:
df.columns = ['Index', 'Course_ID', 'Course_Name', 'Credits', 'Department']

#### Reset Index after dropping rows

In [35]:
df = df.reset_index(drop = True)

In [32]:
def is_number(value):
    try:
        float(value)
        return True
    except ValueError:
        return False

In [36]:
index_position = df[~df['Index'].apply(is_number)]
print(index_position)

                               Index Course_ID Course_Name Credits Department
0               1. Giáo dục thể chất       NaN         NaN     NaN        NaN
1                           Bắt Buộc       NaN         NaN     NaN        NaN
3                            Tự Chọn       NaN         NaN     NaN        NaN
31   2. Kiến thức giáo dục đại cương       NaN         NaN     NaN        NaN
32                          Bắt Buộc       NaN         NaN     NaN        NaN
38                     3. Chuyên sâu       NaN         NaN     NaN        NaN
39                           Tự Chọn       NaN         NaN     NaN        NaN
50                       4. Thực tập       NaN         NaN     NaN        NaN
51                          Bắt Buộc       NaN         NaN     NaN        NaN
53                 5. Học phần chung       NaN         NaN     NaN        NaN
54                          Bắt Buộc       NaN         NaN     NaN        NaN
59                           Tự Chọn       NaN         NaN     NaN        NaN
73            6. Học phần của trường       NaN         NaN     NaN        NaN
74                          Bắt Buộc       NaN         NaN     NaN        NaN
79             7. Học phần của ngành       NaN         NaN     NaN        NaN
80                          Bắt Buộc       NaN         NaN     NaN        NaN
85                    8. Cơ sở ngành       NaN         NaN     NaN        NaN
86                          Bắt Buộc       NaN         NaN     NaN        NaN
92                9. Kiến thức ngành       NaN         NaN     NaN        NaN
93                          Bắt Buộc       NaN         NaN     NaN        NaN
103                          Tự Chọn       NaN         NaN     NaN        NaN

In [40]:
df = df.drop(df.index[0:31])
print(df)

                               Index Course_ID  \
31   2. Kiến thức giáo dục đại cương       NaN
32                          Bắt Buộc       NaN
33                                29  LLDL1102
34                                30  LLNL1105
35                                31  LLNL1106
..                               ...       ...
109                               89  TIHT1122
110                               90  TIHT1123
111                               91  TIKT1106
112                               92  TIKT1129
113                               93  TIKT1134

                                           Course_Name Credits  \
31                                                 NaN     NaN
32                                                 NaN     NaN
33                      Lịch sử Đảng Cộng sản Việt Nam       2
34                               Triết học Mác - Lênin       3
35                       Kinh tế chính trị Mác - Lênin       2
..                                                 ...     ...
109                                  Quản trị tri thức       3
110  Ứng dụng trí tuệ nhân tạo trong kinh doanh và ...       3
111                               Mạng và truyền thông       3
112                        Hệ thống thương mại điện tử       3
113                        Phát triển các ứng dụng WEB       3

                                 Department
31                                      NaN
32                                      NaN
33                   Khoa Lý luận chính trị
34                   Khoa Lý luận chính trị
35                   Khoa Lý luận chính trị
..                                      ...
109  Viện Công nghệ thông tin và Kinh tế số
110  Viện Công nghệ thông tin và Kinh tế số
111  Viện Công nghệ thông tin và Kinh tế số
112  Viện Công nghệ thông tin và Kinh tế số
113  Viện Công nghệ thông tin và Kinh tế số

[83 rows x 5 columns]

In [42]:
df = df.reset_index(drop = True)
df

,Index,Course_ID,Course_Name,Credits,Department
0,2. Kiến thức giáo dục đại cương,NaN,NaN,NaN,NaN
1,Bắt Buộc,NaN,NaN,NaN,NaN
2,29,LLDL1102,Lịch sử Đảng Cộng sản Việt Nam,2,Khoa Lý luận chính trị
3,30,LLNL1105,Triết học Mác - Lênin,3,Khoa Lý luận chính trị
4,31,LLNL1106,Kinh tế chính trị Mác - Lênin,2,Khoa Lý luận chính trị
...,...,...,...,...,...
78,89,TIHT1122,Quản trị tri thức,3,Viện Công nghệ thông tin và Kinh tế số
79,90,TIHT1123,Ứng dụng trí tuệ nhân tạo trong kinh doanh và ...,3,Viện Công nghệ thông tin và Kinh tế số
80,91,TIKT1106,Mạng và truyền thông,3,Viện Công nghệ thông tin và Kinh tế số
81,92,TIKT1129,Hệ thống thương mại điện tử,3,Viện Công nghệ thông tin và Kinh tế số
82,93,TIKT1134,Phát triển các ứng dụng WEB,3,Viện Công nghệ thông tin và Kinh tế số

In [47]:
output_file_path = 'DOUBLE MAJOR/DoubleMajor_MIS_Cleaned.xlsx'
df.to_excel(output_file_path, index=False)